version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - DENO_ENV=development
    networks:
      - farmit-network

networks:
  farmit-network:
    driver: bridge
