CREATE TABLE farm_plots (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    x_coord INTEGER NOT NULL,
    y_coord INTEGER NOT NULL,
    plot_type plot_type_enum DEFAULT 'locked',
    is_watered BOOLEAN DEFAULT FALSE,
    last_watered_at TIMESTAMP,
    crop_id INTEGER REFERENCES crops(id),
    planted_at TIMESTAMP,
    growth_stage INTEGER DEFAULT 0,
    structure_type structure_type_enum,
    structure_health INTEGER DEFAULT 100,
    last_maintained_at TIMESTAMP,
    purchase_date TIMESTAMP,
    purchase_price INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (user_id, x_coord, y_coord),
    CONSTRAINT valid_coordinates CHECK (x_coord >= 0 AND x_coord < 100 AND y_coord >= 0 AND y_coord < 100),
    CONSTRAINT valid_growth CHECK (growth_stage >= 0 AND growth_stage <= 100),
    CONSTRAINT valid_structure_health CHECK (structure_health >= 0 AND structure_health <= 100),
    CONSTRAINT valid_purchase_price CHECK (purchase_price > 0),
    CONSTRAINT valid_farm_plot_data CHECK (validate_farm_plot(x_coord, y_coord, growth_stage))
);
