name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.6

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: npm ci

      - name: Install dependencies (Backend)
        working-directory: ./backend
        run: deno install

      - name: Run Deno fmt (Backend)
        working-directory: ./backend
        run: deno fmt

      # - name: Run Tests (Backend)
      #   working-directory: ./backend
      #   run: deno test
